# -*- coding: utf-8 -*-
"""kekerasan kabupaten & kota.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LHaJRI-qgQUqLgrFuVNrqR_Nm2_5-ov3
"""

import io
import pandas as pd
from google.colab import files

print("Silakan pilih dan upload kedua file CSV ('dataset_kota_sukabumi.csv' & 'dataset_kabupaten_sukabumi.csv') secara bersamaan...")
uploaded = files.upload()

df_kota, df_kab = None, None

# Mengidentifikasi file secara otomatis berdasarkan nama filenya
for file_name in uploaded.keys():
    if 'kota' in file_name.lower():
        df_kota = pd.read_csv(io.BytesIO(uploaded[file_name]))
        print(f"-> Berhasil membaca data Kota Sukabumi dari file: {file_name}")
    elif 'kab' in file_name.lower() or 'kabupaten' in file_name.lower():
        df_kab = pd.read_csv(io.BytesIO(uploaded[file_name]))
        print(f"-> Berhasil membaca data Kabupaten Sukabumi dari file: {file_name}")

if df_kota is not None and df_kab is not None:
    print("\n[SUKSES] Kedua dataset berhasil dimuat ke dalam memori.")
    print("Silakan lanjut jalankan Cell 2 untuk melakukan agregasi data!")
else:
    print("\n[ERROR] Gagal memuat! Pastikan kamu memilih kedua file sekaligus saat tombol upload muncul.")

import numpy as np

try:
    # 1. Membuat daftar tahun historis lengkap (2017-2025)
    daftar_tahun = np.arange(2017, 2026)

    # Kategori bentuk kekerasan sesuai dataset asli
    kategori_kekerasan = ['FISIK', 'PSIKIS', 'SEKSUAL', 'EKSPLOITASI', 'TRAFFICKING', 'PENELANTARAN', 'LAINNYA']

    # 2. Proses Agregasi per Kasus untuk KOTA SUKABUMI
    # Mengelompokkan data berdasarkan tahun dan bentuk kekerasan
    kota_pivot = df_kota.groupby(['tahun', 'bentuk_kekerasan'])['jumlah_korban'].sum().unstack(fill_value=0)
    # Memastikan tahun dari 2017 tetap masuk lengkap walaupun jumlah korbannya 0
    kota_pivot = kota_pivot.reindex(index=daftar_tahun, columns=kategori_kekerasan, fill_value=0)

    # 3. Proses Agregasi per Kasus untuk KABUPATEN SUKABUMI
    kab_pivot = df_kab.groupby(['tahun', 'bentuk_kekerasan'])['jumlah_korban'].sum().unstack(fill_value=0)
    kab_pivot = kab_pivot.reindex(index=daftar_tahun, columns=kategori_kekerasan, fill_value=0)

    # 4. Total korban per tahun untuk kebutuhan model regresi utama
    total_kota_tahunan = kota_pivot.sum(axis=1).values
    total_kab_tahunan = kab_pivot.sum(axis=1).values

    print("[SUKSES] Data Kota dan Kabupaten berhasil dipisahkan!")
    print(f"Data mencakup {len(kategori_kekerasan)} jenis kasus kekerasan dari tahun 2017 hingga 2025.")
    print("Silakan lanjut jalankan Cell 3 untuk menghitung Model Regresi!")

except NameError:
    print("[ERROR] Variabel dataframe belum terbentuk. Pastikan Cell 1 sudah sukses dijalankan!")

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

try:
    X_historis = daftar_tahun.reshape(-1, 1)
    tahun_prediksi = np.arange(2026, 2035)
    X_prediksi = tahun_prediksi.reshape(-1, 1)

    # === MODEL REGRESI KOTA SUKABUMI ===
    model_kota = LinearRegression()
    model_kota.fit(X_historis, total_kota_tahunan)

    fitted_kota = model_kota.predict(X_historis)
    prediksi_kota = model_kota.predict(X_prediksi)
    rmse_kota = np.sqrt(mean_squared_error(total_kota_tahunan, fitted_kota))
    r2_kota = r2_score(total_kota_tahunan, fitted_kota)

    # === MODEL REGRESI KABUPATEN SUKABUMI ===
    model_kab = LinearRegression()
    model_kab.fit(X_historis, total_kab_tahunan)

    fitted_kab = model_kab.predict(X_historis)
    prediksi_kab = model_kab.predict(X_prediksi)
    rmse_kab = np.sqrt(mean_squared_error(total_kab_tahunan, fitted_kab))
    r2_kab = r2_score(total_kab_tahunan, fitted_kab)

    print("[SUKSES] Model matematika Regresi Linear selesai dihitung.")
    print(f"Model Kota      -> Slope: {model_kota.coef_[0]:.2f} | R²: {r2_kota:.4f}")
    print(f"Model Kabupaten -> Slope: {model_kab.coef_[0]:.2f} | R²: {r2_kab:.4f}")
    print("Silakan lanjut ke Cell 4 untuk melihat kesimpulan statistika deskriptif data asli!")

except NameError:
    print("[ERROR] Variabel dari Cell 2 tidak ditemukan. Tolong jalankan Cell 2 terlebih dahulu.")

try:
    print("="*60)
    print(" KESIMPULAN ANALISIS DATASET ASLI (HISTORIS 2017-2025)")
    print("="*60)

    # --- Analisis Kota Sukabumi ---
    idx_max_kota = np.argmax(total_kota_tahunan)
    tahun_max_kota = daftar_tahun[idx_max_kota]
    nilai_max_kota = total_kota_tahunan[idx_max_kota]

    kategori_dominan_kota = kota_pivot.sum().idxmax()
    jumlah_dominan_kota = kota_pivot.sum().max()

    print(f"A. KOTA SUKABUMI:")
    print(f"   - Total kasus korban tertinggi terjadi pada TAHUN: {tahun_max_kota} dengan total {int(nilai_max_kota)} korban.")
    print(f"   - Dari 7 jenis kasus, yang PALING BESAR/DOMINAN adalah kekerasan bentuk '{kategori_dominan_kota}'")
    print(f"     dengan total kumulatif sebanyak {int(jumlah_dominan_kota)} korban selama periode analisis.")
    print(f"   - Hasil Model: Tren diproyeksikan {'NAIK' if model_kota.coef_[0] > 0 else 'TURUN'} ({model_kota.coef_[0]:+.2f} kasus/tahun).\n")

    # --- Analisis Kabupaten Sukabumi ---
    idx_max_kab = np.argmax(total_kab_tahunan)
    tahun_max_kab = daftar_tahun[idx_max_kab]
    nilai_max_kab = total_kab_tahunan[idx_max_kab]

    kategori_dominan_kab = kab_pivot.sum().idxmax()
    jumlah_dominan_kab = kab_pivot.sum().max()

    print(f"B. KABUPATEN SUKABUMI:")
    print(f"   - Total kasus korban tertinggi terjadi pada TAHUN: {tahun_max_kab} dengan total {int(nilai_max_kab)} korban.")
    print(f"   - Dari 7 jenis kasus, yang PALING BESAR/DOMINAN adalah kekerasan bentuk '{kategori_dominan_kab}'")
    print(f"     dengan total kumulatif sebanyak {int(jumlah_dominan_kab)} korban selama periode analisis.")
    print(f"   - Hasil Model: Tren diproyeksikan {'NAIK' if model_kab.coef_[0] > 0 else 'TURUN'} ({model_kab.coef_[0]:+.2f} kasus/tahun).")
    print("="*60)
    print("Silakan jalankan Cell 5 untuk menampilkan visualisasi grafik perbandingan wilayah!")

except NameError:
    print("[ERROR] Pastikan Cell 2 dan Cell 3 sudah dieksekusi dengan benar.")

import matplotlib.pyplot as plt

try:
    # 1. PENYETELAN TEMA VISUALISASI
    plt.rcParams['text.color'] = '#e8eaf0'
    plt.rcParams['axes.labelcolor'] = '#e8eaf0'
    plt.rcParams['xtick.color'] = '#a9afc2'
    plt.rcParams['ytick.color'] = '#a9afc2'
    plt.rcParams['axes.edgecolor'] = '#252a38'

    # Palet warna untuk 7 bentuk kekerasan
    WARNA_7_KASUS = {
        'FISIK': '#ef5350', 'PSIKIS': '#4fc3f7', 'SEKSUAL': '#f5a623',
        'EKSPLOITASI': '#ab47bc', 'TRAFFICKING': '#26a69a',
        'PENELANTARAN': '#66bb6a', 'LAINNYA': '#888888'
    }

    fig, axes = plt.subplots(2, 2, figsize=(18, 16))
    fig.patch.set_facecolor('#0d0f14')

    tahun_gabung = np.concatenate([daftar_tahun, tahun_prediksi])

    # ----------------------------------------------------
    # PLOT 1: REGRESI LINEAR KOTA SUKABUMI (Kiri Atas)
    # ----------------------------------------------------
    ax = axes[0, 0]
    ax.set_facecolor('#13161e')
    ax.grid(True, alpha=0.15, color='#7a8099')
    ax.scatter(daftar_tahun, total_kota_tahunan, color='#4fc3f7', s=80, label='Data Aktual CSV', zorder=5)
    ax.plot(daftar_tahun, fitted_kota, color='#ef5350', linewidth=2, label='Garis Regresi Historis')
    ax.plot(tahun_prediksi, prediksi_kota, color='#f5a623', linestyle='--', linewidth=2, label='Proyeksi (2026-2034)')
    ax.axvline(x=2025.5, color='#252a38', linestyle=':')
    ax.set_title(f"Kota Sukabumi - Tren Regresi (R² = {r2_kota:.3f})", fontweight='bold', pad=10)
    ax.set_xticks(tahun_gabung)
    ax.set_xticklabels(tahun_gabung, rotation=45, fontsize=8)
    ax.legend(facecolor='#1a1e28', edgecolor='#252a38')

    # ----------------------------------------------------
    # PLOT 2: REGRESI LINEAR KABUPATEN SUKABUMI (Kanan Atas)
    # ----------------------------------------------------
    ax = axes[0, 1]
    ax.set_facecolor('#13161e')
    ax.grid(True, alpha=0.15, color='#7a8099')
    ax.scatter(daftar_tahun, total_kab_tahunan, color='#26a69a', s=80, label='Data Aktual CSV', zorder=5)
    ax.plot(daftar_tahun, fitted_kab, color='#ef5350', linewidth=2, label='Garis Regresi Historis')
    ax.plot(tahun_prediksi, prediksi_kab, color='#f5a623', linestyle='--', linewidth=2, label='Proyeksi (2026-2034)')
    ax.axvline(x=2025.5, color='#252a38', linestyle=':')
    ax.set_title(f"Kabupaten Sukabumi - Tren Regresi (R² = {r2_kab:.3f})", fontweight='bold', pad=10)
    ax.set_xticks(tahun_gabung)
    ax.set_xticklabels(tahun_gabung, rotation=45, fontsize=8)
    ax.legend(facecolor='#1a1e28', edgecolor='#252a38')

    # ----------------------------------------------------
    # PLOT 3: PERKEMBANGAN 7 KASUS KOTA (Kiri Bawah)
    # ----------------------------------------------------
    ax = axes[1, 0]
    ax.set_facecolor('#13161e')
    ax.grid(True, alpha=0.15, color='#7a8099')
    for kolom in kota_pivot.columns:
        ax.plot(daftar_tahun, kota_pivot[kolom].values, marker='o', color=WARNA_7_KASUS[kolom], label=kolom)
    ax.set_title("Kota Sukabumi - Perkembangan 7 Kategori Kasus", fontweight='bold', pad=10)
    ax.set_xticks(daftar_tahun)
    ax.legend(facecolor='#1a1e28', edgecolor='#252a38', fontsize=8)

    # ----------------------------------------------------
    # PLOT 4: PERKEMBANGAN 7 KASUS KABUPATEN (Kanan Bawah)
    # ----------------------------------------------------
    ax = axes[1, 1]
    ax.set_facecolor('#13161e')
    ax.grid(True, alpha=0.15, color='#7a8099')
    for kolom in kab_pivot.columns:
        ax.plot(daftar_tahun, kab_pivot[kolom].values, marker='o', color=WARNA_7_KASUS[kolom], label=kolom)
    ax.set_title("Kabupaten Sukabumi - Perkembangan 7 Kategori Kasus", fontweight='bold', pad=10)
    ax.set_xticks(daftar_tahun)
    ax.legend(facecolor='#1a1e28', edgecolor='#252a38', fontsize=8)

    plt.tight_layout()
    plt.show()

except NameError:
    print("[ERROR] Komponen grafik tidak lengkap. Selesaikan eksekusi cell sebelumnya.")

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

try:
    # rentang tahun prediksi baru sesuai permintaan (2026 s.d 2036)
    tahun_prediksi_baru = np.arange(2026, 2037)
    X_prediksi_baru = tahun_prediksi_baru.reshape(-1, 1)
    X_hist = daftar_tahun.reshape(-1, 1)

    # Dictionary untuk menyimpan hasil prediksi matriks
    prediksi_per_kasus_kota = {}
    prediksi_per_kasus_kab = {}

    kesimpulan_tren_kota = []
    kesimpulan_tren_kab = []

    print("="*75)
    # --- PROYEKSI KOTA SUKABUMI PER KATEGORI ---
    for kasus in kategori_kekerasan:
        y_hist_kota = kota_pivot[kasus].values

        # Cek jika data historis kosong/nol semua agar tidak bias
        if np.sum(y_hist_kota) == 0:
            pred_kota = np.zeros(len(tahun_prediksi_baru))
            status = "TETAP (0 Kasus)"
        else:
            model = LinearRegression()
            model.fit(X_hist, y_hist_kota)
            pred_kota = model.predict(X_prediksi_baru)
            # Batasi nilai prediksi agar tidak minus (karena jumlah korban tidak mungkin negatif)
            pred_kota = np.maximum(0, pred_kota)

            slope = model.coef_[0]
            if slope > 0.1: status = "↑ NAIK"
            elif slope < -0.1: status = "↓ TURUN"
            else: status = "→ TETAP"

        prediksi_per_kasus_kota[kasus] = pred_kota
        kesimpulan_tren_kota.append([kasus, status, round(pred_kota[0], 1), round(pred_kota[-1], 1)])

    # --- PROYEKSI KABUPATEN SUKABUMI PER KATEGORI ---
    for kasus in kategori_kekerasan:
        y_hist_kab = kab_pivot[kasus].values

        if np.sum(y_hist_kab) == 0:
            pred_kab = np.zeros(len(tahun_prediksi_baru))
            status = "TETAP (0 Kasus)"
        else:
            model = LinearRegression()
            model.fit(X_hist, y_hist_kab)
            pred_kab = model.predict(X_prediksi_baru)
            pred_kab = np.maximum(0, pred_kab)

            slope = model.coef_[0]
            if slope > 0.1: status = "↑ NAIK"
            elif slope < -0.1: status = "↓ TURUN"
            else: status = "→ TETAP"

        prediksi_per_kasus_kab[kasus] = pred_kab
        kesimpulan_tren_kab.append([kasus, status, round(pred_kab[0], 1), round(pred_kab[-1], 1)])

    # Mengubah ke DataFrame agar tampil berupa tabel yang rapi di Colab
    df_tren_kota = pd.DataFrame(kesimpulan_tren_kota, columns=['Bentuk Kekerasan', 'Prediksi Tren', 'Awal (2026)', 'Akhir (2036)'])
    df_tren_kab = pd.DataFrame(kesimpulan_tren_kab, columns=['Bentuk Kekerasan', 'Prediksi Tren', 'Awal (2026)', 'Akhir (2036)'])

    print("PREDIKSI TREN KATEGORI KASUS - KOTA SUKABUMI (2026-2036):")
    print(df_tren_kota.to_string(index=False))
    print("-"*75)
    print("PREDIKSI TREN KATEGORI KASUS - KABUPATEN SUKABUMI (2026-2036):")
    print(df_tren_kab.to_string(index=False))
    print("="*75)
    print("Silakan lanjut jalankan Cell 7 untuk melihat visualisasinya!")

except NameError:
    print("[ERROR] Pastikan Cell 2 sudah berhasil dijalankan sebelumnya.")

import matplotlib.pyplot as plt

try:
    # Pengaturan tema visual gelap
    plt.rcParams['text.color'] = '#e8eaf0'
    plt.rcParams['axes.labelcolor'] = '#e8eaf0'
    plt.rcParams['xtick.color'] = '#a9afc2'
    plt.rcParams['ytick.color'] = '#a9afc2'
    plt.rcParams['axes.edgecolor'] = '#252a38'

    WARNA_7_KASUS = {
        'FISIK': '#ef5350', 'PSIKIS': '#4fc3f7', 'SEKSUAL': '#f5a623',
        'EKSPLOITASI': '#ab47bc', 'TRAFFICKING': '#26a69a',
        'PENELANTARAN': '#66bb6a', 'LAINNYA': '#888888'
    }

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(16, 14))
    fig.patch.set_facecolor('#0d0f14')

    # ----------------------------------------------------
    # GRAFIK 1: PROYEKSI PER KATEGORI - KOTA SUKABUMI
    # ----------------------------------------------------
    ax1.set_facecolor('#13161e')
    ax1.grid(True, alpha=0.1, color='#7a8099')

    for kasus in kategori_kekerasan:
        warna = WARNA_7_KASUS[kasus]
        # Garis Historis (Asli)
        ax1.plot(daftar_tahun, kota_pivot[kasus].values, marker='o', color=warna, label=kasus, linewidth=1.8)
        # Garis Proyeksi (Prediksi)
        ax1.plot(tahun_prediksi_baru, prediksi_per_kasus_kota[kasus], linestyle='--', color=warna, alpha=0.8)

    ax1.axvline(x=2025.5, color='#f5a623', linestyle=':', alpha=0.6)
    ax1.text(2025.7, ax1.get_ylim()[1]*0.9, 'Batas Prediksi (2026) →', color='#f5a623', fontsize=9)
    ax1.set_title("Proyeksi Tren 7 Jenis Kasus Kekerasan — KOTA SUKABUMI (S.d 2036)", fontweight='bold', pad=12)
    ax1.set_ylabel("Jumlah Korban")
    ax1.set_xticks(np.concatenate([daftar_tahun, tahun_prediksi_baru]))
    ax1.set_xticklabels(np.concatenate([daftar_tahun, tahun_prediksi_baru]), rotation=45, fontsize=8)
    ax1.legend(facecolor='#1a1e28', edgecolor='#252a38', loc='upper left')

    # ----------------------------------------------------
    # GRAFIK 2: PROYEKSI PER KATEGORI - KABUPATEN SUKABUMI
    # ----------------------------------------------------
    ax2.set_facecolor('#13161e')
    ax2.grid(True, alpha=0.1, color='#7a8099')

    for kasus in kategori_kekerasan:
        warna = WARNA_7_KASUS[kasus]
        # Garis Historis (Asli)
        ax2.plot(daftar_tahun, kab_pivot[kasus].values, marker='o', color=warna, label=kasus, linewidth=1.8)
        # Garis Proyeksi (Prediksi)
        ax2.plot(tahun_prediksi_baru, prediksi_per_kasus_kab[kasus], linestyle='--', color=warna, alpha=0.8)

    ax2.axvline(x=2025.5, color='#f5a623', linestyle=':', alpha=0.6)
    ax2.text(2025.7, ax2.get_ylim()[1]*0.9, 'Batas Prediksi (2026) →', color='#f5a623', fontsize=9)
    ax2.set_title("Proyeksi Tren 7 Jenis Kasus Kekerasan — KABUPATEN SUKABUMI (S.d 2036)", fontweight='bold', pad=12)
    ax2.set_ylabel("Jumlah Korban")
    ax2.set_xlabel("Tahun")
    ax2.set_xticks(np.concatenate([daftar_tahun, tahun_prediksi_baru]))
    ax2.set_xticklabels(np.concatenate([daftar_tahun, tahun_prediksi_baru]), rotation=45, fontsize=8)
    ax2.legend(facecolor='#1a1e28', edgecolor='#252a38', loc='upper left')

    plt.tight_layout()
    plt.show()

except NameError:
    print("[ERROR] Selesaikan perhitungan di Cell 6 terlebih dahulu.")